### ISSUE TITLE
get this error from time to time: arbiter.actions - DEBUG: [Errno 16] Device or resource busy

### ISSUE THREAD

**Issue by link89** [chpc-uofu/arbiter2#15]
Sometimes I can see the following error in the debug log

```
24-11-08T15:14:20 - arbiter.actions - DEBUG: Failed to write out the aimed limit (1.9%) and the fallback memory limit (6.4%)!
24-11-08T15:14:20 - arbiter.actions - DEBUG: [Errno 16] Device or resource busy
```

It looks like arbiter may fail to set a new limit to specific user. What's the possible reason of this error and how can I fix it?

**Comment by jay-mckay** [comment]
Hello,

The cgroup memory limit cannot be applied if it is lower than the cgroups *active* memory usage. Active in this case means memory that cannot be swapped out (i.e. swap not available, unswappable kernel pages). Arbiter is aware of this, which is why it has a fallback value - something to try and apply if it cannot set the initial limit. In your case, it is falling at setting the fallback value of 6.4%. This means that the cgroup you are trying to modify is likely using more that 6.4% of the system memory. 

For a better description of this, see [here](https://unix.stackexchange.com/questions/555080/using-cgroup-to-limit-program-memory-as-its-running).

As for fixing this issue, you can try to enable swapping. If it is already enabled, then you will likely need to configure different status quotas - i.e. if the base status memory quota is 10%, you will have an easier time limiting to 6% as opposed to a base quota of 50%.

**Comment by link89** [comment]
Lesson learned, thank you for your sharing @jay-mckay 

> The cgroup memory limit cannot be applied if it is lower than the cgroups active memory usage.

In this case, can I config Arbiter to kill processes that possess excessed resource if Arbiter fail to limit their resource?

**Comment by jay-mckay** [comment]
Arbiter does not have the ability to kill processes. This was an intentional design decision, as we do not ever want to accidentally kill an important process.
